// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutInfo: typeof import('./src/components/AboutInfo/index.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    GetJsonParase: typeof import('./src/components/GetJsonParase/index.vue')['default']
    TableSource: typeof import('./src/components/TableSource/index.vue')['default']
    UploadExcel: typeof import('./src/components/UploadExcel/index.vue')['default']
  }
}

export { }
